---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - lvmsimple.hexin.io
  resources:
  - hxlvms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lvmsimple.hexin.io
  resources:
  - hxlvms/finalizers
  verbs:
  - update
- apiGroups:
  - lvmsimple.hexin.io
  resources:
  - hxlvms/status
  verbs:
  - get
  - patch
  - update
